apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.userDb.username }}
  password: {{ .Values.userDb.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: post-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.postDb.username }}
  password: {{ .Values.postDb.password }}
