apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service-pod
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post-service-pod
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071

---

apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5440
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: post-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post-db
  ports:
    - protocol: TCP
      port: 5441
      targetPort: 5432