apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: posting-system-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-pod
  template:
    metadata:
      labels:
        app: user-service-pod
    spec:
      containers:
        - name: user-service-container
          image: epamvolodymyrsemerkov/user-service:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: user-service-pod-config
          env:
            - name: DB_URL
              value: jdbc:postgresql://$(USER_DB_SERVICE_SERVICE_HOST):$(USER_DB_SERVICE_SERVICE_PORT)/user

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  namespace: posting-system-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service-pod
  template:
    metadata:
      labels:
        app: post-service-pod
    spec:
      containers:
        - name: post-service-container
          image: epamvolodymyrsemerkov/post-service:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: post-service-pod-config
          env:
            - name: DB_URL
              value: jdbc:postgresql://$(POST_DB_SERVICE_SERVICE_HOST):$(POST_DB_SERVICE_SERVICE_PORT)/post
            - name: USER_SERVICE_URL
              value: http://$(USER_SERVICE_SERVICE_HOST):$(USER_SERVICE_SERVICE_PORT)
