apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-pv
  namespace: posting-system-ns
  labels:
    app: user-service-pod
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/posting-system/users"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-service-pv
  namespace: posting-system-ns
  labels:
    app: post-service-pod
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/posting-system/posts"
