apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-pvc
  namespace: posting-system-ns
  labels:
    app: user-service-pod
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
