apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-pvc
  namespace: posting-system-ns
  labels:
    app: user-service-pod
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-service-pvc
  namespace: posting-system-ns
  labels:
    app: post-service-pod
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
