apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: posting-system-ns
spec:
  type: NodePort
  selector:
    app: user-service-pod
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30100

---

apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: posting-system-ns
spec:
  type: NodePort
  selector:
    app: post-service-pod
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30101
